site_name: OnlyDocs
site_description: Docs D'onlymore
#site_author: OpenFaaS Authors
#site_url: https://docs.openfaas.com/


# edit_uri: edit/docs-revamp/docs/
# edit_uri: blob/docs-revamp/docs/

# remote_name: origin
# remote_branch: gh-pages

# Theme and overrides, i.e. language partial
theme:
  name: material
  custom_dir: overrides



  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: false
  palette:
    primary: green
    accent: indigo


# Copyright
copyright: "Copyright &copy; 2021 OpenFaaS Author(s)"

# Options
extra:
  search:
    languages: "en"


extra_css:
  - stylesheets/extra.css

# Page tree
nav:
  - Accueil: index.md
  - Information:
      - Markdown: markdown.md