site_name: OnlyDocs
site_description: Docs d'Alexandre, Le site me permet d'accéder et de rendre publique les documentations que je fais et utilise.
repo_url: https://github.com/Theonlymore/OnlyDocs
edit_uri: edit/main/docs/

# remote_name: origin
# remote_branch: gh-pages

# Theme and overrides, i.e. language partial
theme:
  language: fr
  name: material
  custom_dir: overrides
  features:
    - content.code.annotate 
    - content.tabs.link
  palette:
    - scheme: default
      primary: green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mode nuit
    - scheme: slate
      primary: green
      toggle:
        icon: material/toggle-switch
        name: Mode par défaut


# Copyright
copyright: "Onlydocs d'Alexandre ROCHER"

# Options
extra:
  search:
    languages: "fr"
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/alexandre-rocher-pro
    - icon: fontawesome/brands/github
      link: https://github.com/Theonlymore
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/onlymore
    - icon: fontawesome/solid/link
      link: https://www.onlymore.net


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  
extra_javascript:
  - javascripts/extra.js

extra_css:
  - stylesheets/extra.css

# Page tree
nav:
  - Accueil: index.md
  - Linux:
      - Commande linux: linux/commandeLinux.md
      - Réseau linux:
        - Commande réseau: linux/reseauLinux/commandeReseau.md
        - Filtrage sous linux: linux/reseauLinux/filtrageLinux.md
      - Services:
        - Bind: linux/services/bind.md
        - Apache2 vs NGINX: linux/services/apacheVsNginx.md
        - Apache2: linux/services/apache2.md
        - Nginx: linux/services/nginx.md
        - AgentRelaiDhcp: linux/services/agentRelaiDHCP.md
        - OpenLdap : linux/services/openLdap.md
        - Fail2ban: linux/services/fail2ban.md
        - Borg: linux/services/borgBackup.md
        - Fog: linux/services/fog.md
        - Git: linux/services/git.md
        - Ssh: linux/services/ssh.md
        - Ftp: linux/services/ftp.md
        - NMAP: linux/services/nmap.md
        - Nagios: linux/services/nagios.md
        - ElasticStack:
          - Elasticsearch: linux/services/elasticStack/elasticsearch.md
          - Filebeat: linux/services/elasticStack/filebeat.md
      - CheatsheetInTerminal: linux/cheatSheetInTerminal.md
      - Logs: linux/logs.md
      - Vim: linux/vim.md
      - Man: linux/man.md
      - Find: linux/find.md
      - Cron: linux/cron.md
      - Terminal: linux/terminal.md
  - Docker:
      - Présentation: docker/presentationDocker.md
      - Base de docker: docker/baseDocker.md
      - Réseau dans docker: docker/reseauDocker.md
      - Volumes dans docker: docker/dockerVolumes.md
      - Image docker: docker/imageDocker.md
      - Docker compose: docker/dockerCompose.md
      - Traefik: docker/traefik.md
  - Ansible: 
      - Présentation Ansible: ansible/ansiblePresentation.md
      - Base d'Ansible: ansible/ansibleBase.md
      - Inventory: ansible/ansibleInventory.md
      - Playbook: ansible/ansiblePlaybooks.md
      - Modules:
        - Modules: ansible/modules/ansibleModules.md
        - Docker: ansible/modules/ansibleDocker.md
        - Template: ansible/modules/ansibleTemplate.md
      - Rôles: ansible/ansibleRoles.md
      - Vault: ansible/ansibleVault.md
      - Organisation: ansible/ansibleOrga.md
  - Réseau:     
      - 7 couches OSI: reseau/modelOsi.md
      - Cisco:
        - Commande cisco: reseau/cisco/commandeCisco.md
        - Nat: reseau/cisco/ciscoNat.md
        - Hsrp: reseau/cisco/ciscoHsrp.md
      - HP:
        - SwitchHp: reseau/hp/hpSwitch.md
      - Virtualisation:
        - VM: reseau/vm/vm.md
      - Protocole:
        - Les Ports: reseau/protocole/cheatSheetPort.md
        - SNMP: reseau/protocole/SNMP.md
        - FTP: reseau/protocole/ftp.md
        - HSRP: reseau/protocole/ciscoHsrp.md
        - VTP: reseau/protocole/ciscoVtp.md
        - Routage: reseau/protocole/routage.md
        - Checksum: reseau/protocole/checksum.md
      - Principe:
        - MPLS: reseau/principe/mpls.md
        - Sd-WAN: reseau/principe/sd-wan.md
      - Adresse ip: reseau/adresse_ip.md
      - DNS : reseau/dns.md  
      - Dépannage réseau: reseau/depannageReseau.md
      - DevOps: reseau/devOps.md
      - Filtrage: reseau/filtrage.md
      - Supervision: reseau/superVision.md
      - Reverse proxy: reseau/reverseProxy.md
      - Vlan: reseau/vlan.md
      - Mail: reseau/mail.md
      - Radius: reseau/radius.md
      - VPN: reseau/vpn.md
      - NAT et PAT: reseau/nat-pat.md
      - Chiffrement: reseau/chiffrement.md
  - Securite:
    - Info et lien: securite/info.md
    - Fortinet:
      - Fortigate: securite/fortinet/cliFortinet.md
      - Fortigate: securite/fortinet/erreur.md
  - Windows:
    - Windows: windows/windows.md
    - Windows serveur :
      - Base : windows/windowsServeur/base.md
      - Présentation: windows/windowsServeur/windowsServeur.md
      - Diagnostic: windows/windowsServeur/diagnostic.md
      - Active directory: windows/windowsServeur/ad.md
      - Kerberos: windows/windowsServeur/kerberos.md
      - RDP: windows/windowsServeur/rdp.md
      - Partition: windows/windowsServeur/partition.md
      - DHCP: windows/windowsServeur/dhcp.md
      - Observateur d'événement: windows/windowsServeur/observateurEvenement.md
      - Des GPO:
        - GPO: windows/windowsServeur/gpo/adminLocal.md
        - Autres:  windows/windowsServeur/gpo/gpo.md
    - Logicels:
      - vsCode: windows/soft/vsCode.md
      - Terminal: windows/soft/terminal.md
      - Office365:
        - mail: windows/soft/office365/mail.md
    - Master: windows/makeMaster.md
    - Registre: windows/registre.md
  - Entreprise:
    - Support: entreprise/support.md
  - Cloud :
    - Aws - S3 Glacier : aws/s3Glacier.md
  - Langages:
    - Markdown: langage/markdown.md
    - Bash: langage/bash.md
    - AutoHotKey: langage/ahk.md
    - PowerShell: langage/powerShell.md
    - English:
      - Présentation: langage/english/english.md
      - Conjugaison: langage/english/conjugaison.md
    - Python:
      - Présentation: langage/python/python.md
      - Base: langage/python/python2.md
      - Orienté objet: langage/python/pythonObjet.md
    - SQL: langage/sql.md
    - NoSQL: langage/nosql.md
    - Regex: langage/regex.md
  - Hardware:
    - Stockage: hardware/stockage.md
  - Organisation:
    - Gérez votre temps efficacement: organisation/timeEfficiently.md
    - Journée structurer: organisation/structureDays.md
    - La to-do liste: organisation/todo.md
    - Carte mental: organisation/mindmap.md
  - Sites sympas: niceSite.md
  - Tool: tool.md