site_name: OnlyDocs
site_description: Docs d'Alexandre, Le site me permet d'accéder et de rendre publique les documentations que je fais et utilise.
repo_url: https://github.com/Theonlymore/OnlyDocs
edit_uri: edit/main/docs/

# remote_name: origin
# remote_branch: gh-pages

# Theme and overrides, i.e. language partial
theme:
  language: fr
  name: material
  custom_dir: overrides
  features:
    - content.code.annotate 
    - content.tabs.link
  palette:
    - scheme: default
      primary: green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mode nuit
    - scheme: slate
      primary: green
      toggle:
        icon: material/toggle-switch
        name: Mode par défaut


# Copyright
copyright: "Onlydocs d'Alexandre ROCHER"

# Options
extra:
  search:
    languages: "fr"
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/alexandre-rocher-pro
    - icon: fontawesome/brands/github
      link: https://github.com/Theonlymore
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/onlymore
    - icon: fontawesome/solid/link
      link: https://www.onlymore.net


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true 

  
extra_javascript:
  - javascripts/extra.js

extra_css:
  - stylesheets/extra.css

# Page tree
nav:
  - Accueil: index.md
  - Linux:
      - Commande linux: linux/commandeLinux.md
      - Réseau linux:
        - Commande réseau: linux/reseauLinux/commandeReseau.md
        - Filtrage sous linux: linux/reseauLinux/filtrageLinux.md
      - Services:
        - Bind: linux/services/bind.md
        - Apache2 vs NGINX: linux/services/apacheVsNginx.md
        - Apache2: linux/services/apache2.md
        - Nginx: linux/services/nginx.md
        - AgentRelaiDhcp: linux/services/agentRelaiDHCP.md
        - OpenLdap : linux/services/openLdap.md
        - Fail2ban: linux/services/fail2ban.md
        - Borg: linux/services/borgBackup.md
        - Fog: linux/services/fog.md
        - Git: linux/services/git.md
        - Ssh: linux/services/ssh.md
        - Ftp: linux/services/ftp.md
        - NMAP: linux/services/nmap.md
        - Nagios: linux/services/nagios.md
        - ElasticStack:
          - Elasticsearch: linux/services/elasticStack/elasticsearch.md
          - Filebeat: linux/services/elasticStack/filebeat.md
      - Vim: linux/vim.md
      - Man: linux/man.md
      - Find: linux/find.md
      - Cron: linux/cron.md
      - Terminal: linux/terminal.md

  - Docker:
      - Présentation: docker/presentationDocker.md
      - Base de docker: docker/baseDocker.md
      - Réseau dans docker: docker/reseauDocker.md
      - Volumes dans docker: docker/dockerVolumes.md
      - Image docker: docker/imageDocker.md
      - Docker compose: docker/dockerCompose.md
      - Traefik: docker/traefik.md
  - Ansible: 
      - Présentation Ansible: ansible/ansiblePresentation.md
      - Base d'Ansible: ansible/ansibleBase.md
      - Inventory: ansible/ansibleInventory.md
      - Playbook: ansible/ansiblePlaybooks.md
      - Modules:
        - Modules: ansible/modules/ansibleModules.md
        - Docker: ansible/modules/ansibleDocker.md
        - Template: ansible/modules/ansibleTemplate.md
      - Rôles: ansible/ansibleRoles.md
      - Organisation: ansible/ansibleOrga.md
  - Réseau:     
      - 7 couches OSI: reseau/modelOsi.md
      - Cisco:
        - Commande cisco: reseau/cisco/commandeCisco.md
        - Nat: reseau/cisco/ciscoNat.md
        - Hsrp: reseau/cisco/ciscoHsrp.md
      - Protocole:
        - SNMP: reseau/protocole/SNMP.md
        - FTP: reseau/protocole/ftp.md
        - HSRP: reseau/protocole/ciscoHsrp.md
        - VTP: reseau/protocole/ciscoVtp.md
        - Routage: reseau/protocole/routage.md
      - Adresse ip: reseau/adresse_ip.md
      - DNS : reseau/dns.md  
      - Dépannage réseau: reseau/depannageReseau.md
      - DevOps: reseau/devOps.md
      - Filtrage: reseau/filtrage.md
      - Supervision: reseau/superVision.md
      - Reverse proxy: reseau/reverseProxy.md
      - Vlan: reseau/vlan.md
      - Mail: reseau/mail.md
      - Radius: reseau/radius.md
      - VPN: reseau/vpn.md
      - NAT et PAT: reseau/nat-pat.md
      - Chiffrement: reseau/chiffrement.md
  - Windows :
    - Windows: windows/windows.md
    - Windows serveur :
      - Présentation: windows/windowsServeur/windowsServeur.md
      - Diagnostic: windows/windowsServeur/diagnostic.md
      - Active directory: windows/windowsServeur/ad.md
      - GPO: windows/windowsServeur/gpo.md
      - Kerberos: windows/windowsServeur/kerberos.md
      - RDP: windows/windowsServeur/rdp.md
    - Terminal: windows/newTerminal.md
    - vsCode: windows/vsCode.md
    - Registre: windows/registre.md
  - Aws :
    - S3 Glacier : aws/s3Glacier.md
  - Langages:
    - Markdown: langage/markdown.md
    - PowerShell: langage/powerShell.md
    - SQL: langage/sql.md
    - NoSQL: langage/nosql.md
    - Regex: langage/regex.md
  - Organisation:
        Gérez votre temps efficacement: organisation/timeEfficiently.md
        Journée structurer: organisation/structureDays.md
        La to-do liste: organisation/todo.md
        Carte mental: organisation/mindmap.md
  - Sites sympas: niceSite.md