site_name: OnlyDocs
site_description: Docs D'onlymore
#site_author: OpenFaaS Authors
#site_url: https://docs.openfaas.com/


# edit_uri: edit/docs-revamp/docs/
# edit_uri: blob/docs-revamp/docs/

# remote_name: origin
# remote_branch: gh-pages

# Theme and overrides, i.e. language partial
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      primary: green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mode nuit
    - scheme: slate
      primary: green
      toggle:
        icon: material/toggle-switch
        name: Mode par défaut


  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: false



# Copyright
copyright: "Copyright &copy; 2021 OpenFaaS Author(s)"

# Options
extra:
  search:
    languages: "en"


extra_css:
  - stylesheets/extra.css

# Page tree
nav:
  - Accueil: index.md
  - Linux:
      - Vim: linux/vim.md
      - Cron: linux/cron.md
      - Commande réseau: linux/commandeReseau.md
      - Commande linux: linux/linuxBase.md
  - Docker:
      - Présentation: docker/presentationDocker.md
      - Base de docker: docker/baseDocker.md
      - Réseau dans docker: docker/reseauDocker.md
      - Image docker: docker/imageDocker.md
      - Docker compose: docker/dockerCompose.md
  - Réseau:     
      - Cisco:
        - Commande cisco: reseau/cisco/commandeCisco.md  
      - Adresse ip: reseau/adresse_ip.md
      - Future docs: reseau/futures_docs.md
  - Autre:
      - Markdown: autre/markdown.md