site_name: OnlyDocs
site_description: Docs d'Alexandre, Le site me permet d'accéder et de rendre publique les documentations que je fais et utilise.
repo_url: https://github.com/Theonlymore/OnlyDocs

# edit_uri: edit/docs-revamp/docs/
# edit_uri: blob/docs-revamp/docs/

# remote_name: origin
# remote_branch: gh-pages

# Theme and overrides, i.e. language partial
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      primary: green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mode nuit
    - scheme: slate
      primary: green
      toggle:
        icon: material/toggle-switch
        name: Mode par défaut

plugins:
  - search
  - git-revision-date-localized:
      type: timeago
      timezone: Europe/Amsterdam
      locale: en
      fallback_to_build_date: false
      enable_creation_date: true


  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: false



# Copyright
copyright: "Onlydocs <3"

# Options
extra:
  search:
    languages: "en"

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - stylesheets/extra.css

# Page tree
nav:
  - Accueil: index.md
  - Linux:
      - Réseau linux:
        - Commande réseau: linux/reseauLinux/commandeReseau.md
        - Filtrage sous linux: linux/reseauLinux/filtrageLinux.md
      - Services:
        - Bind: linux/services/bind.md
        - OpenLda: linux/services/openLdap.md
        - Apache2 vs NGINX: linux/services/apacheVsNginx.md
        - Apache2: linux/services/apache2.md
      - Vim: linux/vim.md
      - Cron: linux/cron.md
      - Commande linux: linux/commandeLinux.md
  - Docker:
      - Présentation: docker/presentationDocker.md
      - Base de docker: docker/baseDocker.md
      - Réseau dans docker: docker/reseauDocker.md
      - Volumes dans docker: docker/dockerVolumes.md
      - Image docker: docker/imageDocker.md
      - Docker compose: docker/dockerCompose.md
  - Réseau:     
      - Cisco:
        - Commande cisco: reseau/cisco/commandeCisco.md
      - Dépannage réseau: reseau/depannageReseau.md
      - DNS : reseau/dns.md  
      - Adresse ip: reseau/adresse_ip.md
      - Filtrage: reseau/filtrage.md
      - Future docs: reseau/futures_docs.md
  - Windows :
    - Windows serveur :
      - Présentation: windows/windowsServeur/windowsServeur.md
      - Active directory: windows/windowsServeur/ad.md
  - Aws :
    - S3 Glacier : aws/s3Glacier.md
  - Langage:
    - Markdown: langage/markdown.md
  - Sites sympas: niceSite.md