apiVersion: batch/v1
kind: Job
metadata:
  name: build-onlydocs
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
        - "--dockerfile=Dockerfile"
        - "--context=git://github.com/Theonlymore/OnlyDocs.git"
        - "--destination=registry.default.svc.cluster.local:5000/onlydocs:latest"
        - "--insecure"
        - "--skip-tls-verify"
