apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: onlydocs
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: docs.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: onlydocs
            port:
              number: 80
