name: DeployToS3

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Theonlymore/MkdocsToSFTP@main
      with:
          username: mkdocs
          server: rocheralexandre.com
          port: 22
          local_path: './github/workspace/site/*'
          remote_path: '/apps/web/mkdocs'
          sftp_only: true
          password: ${{ secrets.SFTP_PASSWORD }}
